[package]
name = "network"
version = "0.1.0"
authors = ["yanggaofeng <yanggf23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio="0.6.2"
dns-lookup="1.0.1"
protocol = { path="../protocol" }
